### ISSUE TITLE
Dataset description

### ISSUE THREAD

**Issue by yuanchun-li** [Retsediv/WIFI_CSI_based_HAR#24]
Hi @Retsediv,
Thank you for the great work.
I downloaded the data from this [link](https://drive.google.com/file/d/1geOFNDn-Q_K4R5W-ECHj7D__bU96_j2v/view?usp=sharing), but I was unable to understand the data schema. Cloud you please provide some details about the meanings of rows and columns in each file?

**Comment by Retsediv** [comment]
Hi, @yuanchun-li 

So, the dataset is divided by rooms and trials in those rooms.

`data.csv` is CSI data from the router. Depending on whether it was collected on 2 GHz or 5 GHz frequency, it will consist of 56 or 114 columns with values 0....55 or 113 (showing the frequency). So, this is the number of subcarriers of one antenna pair (56 or 114). After that, you have `# of subcarriers` x `# of antenna pairs` columns for amplitude data. And again, the same columns for the phase. So, one entry represents one data packet.
You can check more here https://github.com/Retsediv/WIFI_CSI_based_HAR/blob/master/model_for_har/dataset.py (`read_csi_data_from_csv()`)

`labels.csv` has labels for each data packet.

**Comment by yuanchun-li** [comment]
Thank you!
